# --- CONFIG ---
$server   = "rdp.rewebly.com"
$username = "corp\Administrator"
$password = "!Mamoute901901a"
$rdpPath  = "$env:TEMP\RemoteApp_PowerShellISE.rdp"

# --- CREATE MODIFIED RDP FILE (SIGNATURE WILL BE ADDED LATER) ---
$rdpContent = @"
redirectclipboard:i:1
redirectprinters:i:1
redirectcomports:i:1
redirectsmartcards:i:1
devicestoredirect:s:*
drivestoredirect:s:*
redirectdrives:i:1
session bpp:i:32
prompt for credentials on client:i:0
span monitors:i:0
use multimon:i:0
remoteapplicationmode:i:1
server port:i:3389
allow font smoothing:i:1
promptcredentialonce:i:0
videoplaybackmode:i:1
audiocapturemode:i:1
gatewayusagemethod:i:0
gatewayprofileusagemethod:i:1
gatewaycredentialssource:i:0
full address:s:$server
alternate shell:s:||PowerShell_ISE
remoteapplicationprogram:s:||PowerShell_ISE
remoteapplicationname:s:Windows PowerShell ISE (x86)
remoteapplicationcmdline:s:
workspace id:s:$server
use redirection server name:i:1
loadbalanceinfo:s:tsv://MS Terminal Services Plugin.1.DefaultCollectio
alternate full address:s:$server

screen mode id:i:1
displayconnectionbar:i:0
desktopwidth:i:200
desktopheight:i:150
winposstr:s:0,3,-32000,-32000,-31800,-31800

authentication level:i:2
enablecredsspsupport:i:1

signscope:s:Full Address,Alternate Full Address,Use Redirection Server Name,Server Port,GatewayUsageMethod,GatewayProfileUsageMethod,GatewayCredentialsSource,PromptCredentialOnce,Alternate Shell,RemoteApplicationProgram,RemoteApplicationMode,RemoteApplicationName,RemoteApplicationCmdLine,RedirectDrives,RedirectPrinters,RedirectCOMPorts,RedirectSmartCards,RedirectClipboard,DevicesToRedirect,DrivesToRedirect,LoadBalanceInfo

signscope:s:Full Address,Alternate Full Address,Use Redirection Server Name,Server Port,GatewayUsageMethod,GatewayProfileUsageMethod,GatewayCredentialsSource,PromptCredentialOnce,Alternate Shell,RemoteApplicationProgram,RemoteApplicationMode,RemoteApplicationName,RemoteApplicationCmdLine,RedirectDrives,RedirectPrinters,RedirectCOMPorts,RedirectSmartCards,RedirectClipboard,DevicesToRedirect,DrivesToRedirect,LoadBalanceInfo
signature:s:AQABAAEAAAAqEgAAMIISJgYJKoZIhvcNAQcCoIISFzCCEhMCAQExDzANBglghkgB  ZQMEAgEFADALBgkqhkiG9w0BBwGggg/2MIIFBTCCAu2gAwIBAgIQS6hSk/eaL6Jz  BkuoBI110DANBgkqhkiG9w0BAQsFADBPMQswCQYDVQQGEwJVUzEpMCcGA1UEChMg  SW50ZXJuZXQgU2VjdXJpdHkgUmVzZWFyY2ggR3JvdXAxFTATBgNVBAMTDElTUkcg  Um9vdCBYMTAeFw0yNDAzMTMwMDAwMDBaFw0yNzAzMTIyMzU5NTlaMDMxCzAJBgNV  BAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQwwCgYDVQQDEwNSMTAwggEi  MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDPV+XmxFQS7bRH/sknWHZGUCiM  HT6I3wWd1bUYKb3dtVq/+vbOo76vACFLYlpaPAEvxVgD9on/jhFD68G14BQHlo9v  H9fnuoE5CXVlt8KvGFs3Jijno/QHK20a/6tYvJWuQP/py1fEtVt/eA0YYbwX51TG  u0mRzW4Y0YCF7qZlNrx06rxQTOr8IfM4FpOUurDTazgGzRYSespSdcitdrLCnF2Y  RVxvYXvGLe48E1KGAdlX5jgc3421H5KRmudKHMxFqHJV8LDmowfs/acbZp4/SItx  hHFYyTr6717yW0QrPHTnj7JHwQdqzZq3DZb3EoEmUVQK7GH29/Xi8orIlQ2NAgMB  AAGjgfgwgfUwDgYDVR0PAQH/BAQDAgGGMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggr  BgEFBQcDATASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBS7vMNHpeS8qcbD  pHIMEI2iNeHI6DAfBgNVHSMEGDAWgBR5tFnme7bl5AFzgAiIyBpY9umbbjAyBggr  BgEFBQcBAQQmMCQwIgYIKwYBBQUHMAKGFmh0dHA6Ly94MS5pLmxlbmNyLm9yZy8w  EwYDVR0gBAwwCjAIBgZngQwBAgEwJwYDVR0fBCAwHjAcoBqgGIYWaHR0cDovL3gx  LmMubGVuY3Iub3JnLzANBgkqhkiG9w0BAQsFAAOCAgEAkrHnQTfreZ2B5s3iJeE6  IOmQRJWjgVzPw139vaBw1bGWKCIL0vIozwzn1OZDjCQiHcFCktEJr59L9MhwTyAW  sVrdAfYf+B9haxQnsHKNY67u4s5Lzzfdu6PUzeetUK29v+PsPmI2cJkxp+iN3epi  4hKu9ZzUPSwMqtCceb7qPVxEbpYxY1p91n5PJKBLBX9eb9LU6l8zSxPWV7bK3lG4  XaMJgnT9x3ies7msFtpKK5bDtotij/l0GaKeA97pb5uwD9KgWvaFXMIEt8jVTjLE  vwRdvCn294GPDF08U8lAkIv7tghluaQh1QnlE4SEN4LOECj8dsIGJXpGUk3aU3Kk  Jz9icKy+aUgA+2cP21uh6NcDIS3XyfaZQjmDQ993ChII8SXWupQZVBiIpcWO4RqZ  k3lr7Bz5MUCwzDIA359e57SSq5CCkY0N4B6Vulk7LktfwrdGNVI5BsC9qqxSwSKg  RJeZ9wygIaehbHFHFhcBaMDKpiZlBHyzrsnnlFXCb5s8HKn5LsUgGvB24L7sGNZP  2CX7dhHov+YhD+jozLW2p9W4959Bz2EiRmqDtmiXLnzqTpXbI+suyCsohKRg6Un0  RC47+cpiVwHiXZAW+cn8eiNIjqbVgXLxKPpdzvvtTnOPlC7SQZSYmdunr3Bf9b77  AiC/ZidstK36dRILKz7OA54wggVrMIIDU6ADAgECAhEAghDPsNJA41lEY+C7Y4KL  ADANBgkqhkiG9w0BAQsFADBPMQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJu  ZXQgU2VjdXJpdHkgUmVzZWFyY2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBY  MTAeFw0xNTA2MDQxMTA0MzhaFw0zNTA2MDQxMTA0MzhaME8xCzAJBgNVBAYTAlVT  MSkwJwYDVQQKEyBJbnRlcm5ldCBTZWN1cml0eSBSZXNlYXJjaCBHcm91cDEVMBMG  A1UEAxMMSVNSRyBSb290IFgxMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC  AgEAregkc/QUN/ObnitXKByHvty33ziQjG485legePd1wqL+9Wpu9gBPKNveaIZs  RJO2sWP9FBJrvx/S6jGbIX7RMzy6SPXded+zuP8S8SGaS8GKhnFpSmZmbI9+PHC/  rSkiBvPkwOaAruJLj7eZfpQDn9NHl3yZSCNT6DiuTwpvgy7RSVeMgHS22i/QOI17  A3AhG3XyMDz6j67d2mOr6xZPwo4RS37PC+j/tXcu9LJ7SuBMEiUMcI0DKaDhUyTs  E9nuGb8Qs0qMP4mjYVHerIcHlPRjcewu4m9bmIHhiVw0eWx27zuQYnnm26SaLybF  0BDhDt7ZEI4W+7f3qPfH5QIHmI82CJXn4jeWDTZ1nvsOcrEdm7wD+UkF2IHdBbQq  1kHprAF2lQoP2N/VvRIfNS8oF2zSmMGoCWR3bkc3us6sWV5onX9y1onFBkEpPlk+  3Sb1JMkRp1qjTEAfRqGZtac6UW6GO559cqcSBXhZ7T5ReBULA4+N0C8Fsj57ShxL  cwUS/Mbq4FATfEOTdLPKdOeOHwEI0DDUW3E2tAe6wTAwXEi3gjuYpn1giqKjKYLM  ur2DBBuigwNBodYF8RvCtvCofIY7RqhIKojcdpp2vx9qpT0Zj+s482TeyCsNCij/  99viFULUItAnXeF5/hjncIitTubZizrG3SdRbv+8ZPUzQ08CAwEAAaNCMEAwDgYD  VR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFHm0WeZ7tuXk  AXOACIjIGlj26ZtuMA0GCSqGSIb3DQEBCwUAA4ICAQBVH1ipvLKoUNAMsdgaaSAn  KQisYXVcim74guVpL9X2Vku5uHMQWdMhl37nTHH7stJgrTmoC+oXIVaF8VAOWevO  4FnpuskV74adj4SA9uTpkZDcF5tiG0XwZpXSfG/C6jvvH8/L1q4n8amwyK79fX6a  +iIE6//Zf+qRKyKxFw6P8oo0W1jY/AHJVLm4JsyKiDOJTC2EPILf7pZXBbosu/fE  t8dOO4K+Mcgic3OS0cKApDk5EDMjgkw8n4ayVZgdvimGjCKbnuJrO1c6gnBN3AnH  icsKB01s6F2Oye/Oq8e7tStORdZK0CbM5XLKCGqlleMVofek7cksX6X7/6woAi6+  13u743F7kBbTB15GU3w3B0KM08SWnNWZtSrglRqASK5MOQfOzEekUpUrurj7rdIz  U33lHU1t1aGxx0Jv5kAnNVyjKLcHjeeNM5DnI5/7UJx5bEbVtBWzlm5+mwyWOrhS  LT/WW+H7CMKE/iSoo4narGrhGCqxqENhW9Mf3DuNdvIt6I113xczbD1T+3vLQV//  3KLQYTjhlrisXYs313XVM8CZEa6dQcFydYS+AkFCX2ckSJTRmye+Bz+5uE+BdFHh  erftnSPivuDVKAQTPDEDnt16bI/GBxjGf95Hjj8ongQGz6VUNHe97Imb6RdD31vb  X/6OHleizUCdfmIi2t4YJzCCBXowggRioAMCAQICEga1pVNH9jOek6k+bqfWLhkq  ZzANBgkqhkiG9w0BAQsFADAzMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg  RW5jcnlwdDEMMAoGA1UEAxMDUjEwMB4XDTI1MDcxMTA1NDU0NloXDTI1MTAwOTA1  NDU0NVowGjEYMBYGA1UEAxMPcmRwLnJld2VibHkuY29tMIIBojANBgkqhkiG9w0B  AQEFAAOCAY8AMIIBigKCAYEAlhM3DboxjWdCgxj+aGCKyds/PpibDOV6IaS/tXgJ  iCpjNA4VQNdwfhX2E0Q8kWjJNvvLXW+2tBKTL7AdFc9HXejQGT1kEjOOom5l9FWi  3PvfmEs27wsVGVu2SLLYgPknyg2hYMz76g27EGrpZ6bBX3fHd+GniamynGjgfGN6  KcbaYcc4B4pnp3iEZsKXZQzX/VqTicS0rsceyYflYKJVW0HkG0YyVAnDkhUzLiZC  zUXUHew514QX0Owwn8IlrpZ+Ds1vUwwJ5oXa5rlegIYPxtnA4rOsUfN/d9hXPo+7  ucuQRE9fAz3iRAxzo5Iseu1kaiK5hxcEcyqix0WI1gykHosbBtU+LxtSE6qxyGIv  eCvouEVL4UZIPcn80dCsQTazIs6CJCXVrGrenhT2zrr+84sqnMDg5Gs0vnSTI76O  EsjaH/Snbo8JzSoLB+tTVF/xkQ/tJXGU2l7a3AoL0QWsQfow6Cnl3Qb56yYHspLu  WaYIp/4GZLdhfCgdMrX3lpbhAgMBAAGjggIfMIICGzAOBgNVHQ8BAf8EBAMCBaAw  HQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYD  VR0OBBYEFAkdYiPpsLWAbavBiziPfZUYdp7cMB8GA1UdIwQYMBaAFLu8w0el5Lyp  xsOkcgwQjaI14cjoMDMGCCsGAQUFBwEBBCcwJTAjBggrBgEFBQcwAoYXaHR0cDov  L3IxMC5pLmxlbmNyLm9yZy8wGgYDVR0RBBMwEYIPcmRwLnJld2VibHkuY29tMBMG  A1UdIAQMMAowCAYGZ4EMAQIBMC8GA1UdHwQoMCYwJKAioCCGHmh0dHA6Ly9yMTAu  Yy5sZW5jci5vcmcvMTA0LmNybDCCAQMGCisGAQQB1nkCBAIEgfQEgfEA7wB2ABLx  TjS9U3JMhAYZw48/ehP457Vih4icbTAFhOvlhiY6AAABl/g6QAQAAAQDAEcwRQIg  Y7u0zDHkTechMPN8YYwYU1zYLGgnjwj20FWIYQ6t11sCIQCL3abl+Iv9nzJhDz3u  F/5JExV02dKK4WioBTfwbFiWVQB1AO08S9boBsKkogBX28sk4jgB31Ev7cSGxXAP  IN23Pj/gAAABl/g6R80AAAQDAEYwRAIgLC8up7voCuCOsUd4zSDn24r3g3cqgY2K  dci+7ygk79wCIAKV/YJnyj2IzWwhnu84VNvURVxCyOXPqyG4Qqu/FJkqMA0GCSqG  SIb3DQEBCwUAA4IBAQA6Qsrsxbteg63tqV1GozXbVJlBCjjuA/xI5Q8MvJaz0nSB  CXCnV2bLoM/HQtUXrSJ7/v4YKdGjtbHxziBZKg5FIgljkGd8tpWv+wd5CNeM+Lbs  APUpm4m2cYZJzElxSp1QjvzMlFIOcyQsWxgx+nvOi3qMDjpZzZcgr3d9TLP/UkwQ  TzgSCnFevl1GUKYPAYhAS96mjwxLAef1Q8NNIJVCghCHB+ZN7jkIszluYxn2z9o4  R7nEa5MVKPjgjulw5tn/m21kZgi2XXANglxPefcSEIWx4VNHImspjls65eqsl0TD  /qieilh3KZvilDVqZr/fJizQ9/3gKjVvo5AvJ/EzMYIB9DCCAfACAQEwSTAzMQsw  CQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3MgRW5jcnlwdDEMMAoGA1UEAxMDUjEw  AhIGtaVTR/YznpOpPm6n1i4ZKmcwDQYJYIZIAWUDBAIBBQAwDQYJKoZIhvcNAQEB  BQAEggGADc6Zht6vveKPta3LWnGMQkqlH3ev6zTp8Q2CBi1DIKQjNhAIWPr3A9RX  xjSB1MdEtqzlWh/mynuDYd6YWgpXfZ1tMbaP0m9hXux7l0Fj3pIISlEYOBGJ5Xmk  +wMqqyKJuUyvDe3wMpXUnrPrdMcW2y/FaGw9gh1Ll5qXD/SHN6Dshz2X6jpyj25Z  oNXgjZML+Qw+LMbwSpWQRlx8qwSDNPESut4Xx17SW3Zo2qRrlOjaEFnmjcjuo52M  nObzywqdLf9hVSjJ2K4omoxBvXAnKVC0QzDmcj6w/EpHZk4Ffmcy2pZu3q7Vt07+  OTxMa38XKMFt88cuqdtEPwyklwiiTahc8ywOTs9kLjTIf9lY0M1N4yaPLK/K2yh9  t+k7Z3lVjqMyIY5GGgxDSE8pYmCdUAsueI2WUjjH/fWPlIx+B8wVYteY41h2U3aw  4nnDXL5YfqCeC9NQhQIK4aS3+xN/p8Pj/jHc7axTLrCPug9mCl8I+E6wrWXULLiB  o7oUeBEy

# Save the modified RDP file
$rdpContent | Out-File -FilePath $rdpPath -Encoding ASCII
Write-Host "Modified RDP saved at: $rdpPath"
Write-Host "Remember to PASTE the original broker signature at the end!"

# --- CACHE CREDENTIALS (so no prompt) ---
cmdkey /generic:$server /user:$username /pass:$password | Out-Null

Write-Host "Credentials cached. After adding signature, you can run:"
Write-Host "mstsc.exe `"$rdpPath`""
